version: "3.9"

services:
  web-service:
    container_name: dev-rest-mq-consumer
    build: .
    image: ${IMAGE_MQ_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    env_file:
      - "${ENV_FILE:-.env}"
    restart: always
    expose:
      - "8082"
      - "9082"
    ports:
      - "8082:8082"
      - "9082:9082"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
                          -Xms256m
                          -Xloggc:gc.log
                          -XX:+HeapDumpBeforeFullGC
                          -XX:HeapDumpPath=dump
                          -XX:+PrintGCDetails
                          -XX:+PrintGCDateStamps
                          -XX:+PrintHeapAtGC
    networks:
      - rest


networks:
  rest:
    name: dev-rest_default
    driver: bridge
